spring.application.name=relazioni-pericolose

server.port=9007

# Configurazione del database
spring.datasource.url=jdbc:mysql://localhost/esercitazioni
spring.datasource.username=root
spring.datasource.password=root


# Configurazione di JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




