spring.application.name=magazzino

# Configurazione del database
spring.datasource.url=jdbc:h2:file:./data/magazzino
spring.datasource.username=sa
spring.datasource.password=




spring.h2.console.path=/console
spring.h2.console.enabled=true

# Configurazione di JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=embedded
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.driverClassName=org.h2.Driver
spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql

# Configurazione del server
server.port=9004

# Configurazione del logging
logging.level.org.springframework=INFO
logging.level.it.bogliaccino.magazzino=DEBUG

