spring.application.name=magazzino

#Configurazione del database
spring.datasource.url=jdbc:h2:file:./data/magazzino
  # DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true

#Configurazione di JPA/Hibernate
#con update ogni volta controlla se la tabella c'è, sennò la crea, se c'era già verifica che sia aggiornata
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=never

#Configurazione del server
server.port=9004

#Configurazione del logging
logging.level.org.springframework=INFO
logging.level.org.com.mombelli.magazzino=DEBUG


#Configurazione di CORS, meglio farla man mano nel controller


