spring.application.name=Prj19_Prodotti-Rest


server.port=9006

spring.datasource.url=jdbc:mysql://localhost/esercitazioni
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

